package ar.edu.unlam;

public enum Seleccion {
	
	QATAR, ECUADOR, SENEGAL, PAISES_BAJOS, INGLATERRA, IRAN, EEUU, GALES, ARGENTINA, ARABIA_SAUDITA, MEXICO, POLONIA, FRANCIA, AUSTRALIA, DINAMARCA, TUNEZ, ESPAÑA, COSTA_RICA, ALEMANIA, JAPON, BELGICA, CANADA, MARRUECOS, CROACIA, BRASIL, SERBIA, SUIZA, CAMERUN, PORTUGAL, GHANA, URUGUAY, COREA_DEL_SUR

}
